import { ProductCategory } from '../../src/generated/prisma/enums';
import type { Prisma } from '../../src/generated/prisma/client';
import type { ProductAllergen, ProductDietaryTag } from '../../src/catalog/catalog-preferences';

interface ProductMetadata extends Prisma.InputJsonObject {
  allergens: ProductAllergen[];
  dietaryTags: ProductDietaryTag[];
  containsCoffee: boolean;
  decaffeinated: boolean;
  caffeineFree: boolean;
}

function productMetadata(metadata: ProductMetadata): ProductMetadata {
  return metadata;
}

export const cafeNubeProducts = [
  {
    slug: 'espresso-nube',
    name: 'Espresso Nube',
    description:
      'Shot de espresso preparado con café peruano de temporada. El origen puede variar según el lote disponible.',
    price: '8.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
      notes: ['El origen del café cambia según la temporada'],
    }),
  },
  {
    slug: 'americano',
    name: 'Americano',
    description: 'Espresso con agua caliente. Se puede pedir suave o intenso.',
    price: '10.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso con leche vaporizada y espuma cremosa.',
    price: '12.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'latte',
    name: 'Latte',
    description: 'Espresso con mayor proporción de leche vaporizada.',
    price: '13.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'moca-cacao-peruano',
    name: 'Moca con cacao peruano',
    description: 'Espresso, chocolate peruano y leche vaporizada.',
    price: '15.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'chocolate-caliente-cacao-peruano',
    name: 'Chocolate caliente de cacao peruano',
    description: 'Chocolate preparado con cacao peruano, leche y un toque de panela.',
    price: '14.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'cafe-filtrado-descafeinado',
    name: 'Café filtrado descafeinado',
    description: 'Café descafeinado preparado al momento con método filtrado.',
    price: '11.00',
    currency: 'PEN',
    category: ProductCategory.HOT_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: true,
      caffeineFree: false,
      notes: ['El café descafeinado puede conservar una pequeña cantidad de cafeína'],
    }),
  },
  {
    slug: 'cold-brew-citrico',
    name: 'Cold Brew cítrico',
    description: 'Café extraído en frío durante 16 horas, servido con hielo y piel de naranja.',
    price: '17.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
      extractionHours: 16,
    }),
  },
  {
    slug: 'frappe-nube',
    name: 'Frappé Nube',
    description: 'Café, leche y hielo licuados. Puede pedirse con o sin crema batida.',
    price: '16.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'iced-latte',
    name: 'Iced latte',
    description: 'Espresso con leche fría y hielo.',
    price: '15.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: ['MILK'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'te-helado-maracuya',
    name: 'Té helado de maracuyá',
    description: 'Té negro frío con maracuyá y un toque de hierbaluisa.',
    price: '12.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'espresso-tonic',
    name: 'Espresso tonic',
    description: 'Espresso servido con agua tónica, hielo y piel de limón.',
    price: '16.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: true,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'chicha-morada-especiada',
    name: 'Chicha morada especiada',
    description: 'Bebida fría preparada con maíz morado, piña, canela y clavo de olor.',
    price: '10.00',
    currency: 'PEN',
    category: ProductCategory.COLD_DRINK,
    active: true,
    metadata: productMetadata({
      allergens: [],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
    }),
  },
  {
    slug: 'croissant-mantequilla',
    name: 'Croissant de mantequilla',
    description: 'Croissant horneado durante la mañana. Disponible hasta agotar stock.',
    price: '9.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'MILK', 'EGG'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
      availabilityNote: 'Hasta agotar stock',
    }),
  },
  {
    slug: 'toston-palteado',
    name: 'Tostón palteado',
    description: 'Pan de masa madre, hummus, palta, tomate confitado y semillas.',
    price: '22.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'SESAME'],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
    }),
  },
  {
    slug: 'carrot-cake',
    name: 'Carrot cake',
    description: 'Queque de zanahoria con pecanas y cobertura de queso crema.',
    price: '15.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'MILK', 'EGG', 'TREE_NUTS'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
      availabilityNote: 'Hasta agotar stock',
    }),
  },
  {
    slug: 'panini-caprese',
    name: 'Panini caprese',
    description: 'Pan ciabatta con mozzarella, tomate, albahaca y pesto.',
    price: '19.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'MILK', 'TREE_NUTS'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
    }),
  },
  {
    slug: 'brownie-cacao',
    name: 'Brownie de cacao',
    description: 'Brownie húmedo preparado con cacao peruano y chocolate.',
    price: '11.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'MILK', 'EGG'],
      dietaryTags: ['VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'galleta-vegana-avena-cacao',
    name: 'Galleta vegana de avena y cacao',
    description: 'Galleta de avena, cacao y plátano, preparada sin ingredientes de origen animal.',
    price: '9.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN'],
      dietaryTags: ['VEGAN', 'VEGETARIAN'],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: false,
    }),
  },
  {
    slug: 'sandwich-pollo-pesto',
    name: 'Sándwich de pollo al pesto',
    description: 'Pan de masa madre con pollo, pesto, tomate y queso.',
    price: '21.00',
    currency: 'PEN',
    category: ProductCategory.FOOD,
    active: true,
    metadata: productMetadata({
      allergens: ['GLUTEN', 'MILK', 'TREE_NUTS'],
      dietaryTags: [],
      containsCoffee: false,
      decaffeinated: false,
      caffeineFree: true,
    }),
  },
] as const;

export const cafeNubePromotions = [
  {
    slug: 'frappe-dos-por-uno',
    name: 'Frappé 2x1',
    description:
      'Promoción 2x1 en Frappés Nube, de lunes a jueves entre las 3:00 p. m. y las 5:00 p. m.',
    startsAt: new Date('2026-01-01T05:00:00.000Z'),
    endsAt: null,
    active: true,
    metadata: {
      days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY'],
      startTime: '15:00',
      endTime: '17:00',
      buyQuantity: 2,
      payQuantity: 1,
      channels: ['STORE', 'PICKUP'],
      excludedChannels: ['DELIVERY'],
      stackable: false,
      productSlugs: ['frappe-nube'],
    },
  },
  {
    slug: 'desayuno-nube',
    name: 'Desayuno Nube',
    description:
      'Un cappuccino y un croissant de mantequilla por S/ 18, de lunes a viernes entre las 7:00 a. m. y las 10:00 a. m.',
    startsAt: new Date('2026-01-01T05:00:00.000Z'),
    endsAt: null,
    active: true,
    metadata: {
      days: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY'],
      startTime: '07:00',
      endTime: '10:00',
      promotionalPrice: '18.00',
      regularPrice: '21.00',
      productSlugs: ['cappuccino', 'croissant-mantequilla'],
      alternativeMilkPrice: '3.00',
      restrictions: ['Sujeto a stock de croissants'],
      stackable: false,
    },
  },
  {
    slug: 'viernes-frio',
    name: 'Viernes frío',
    description:
      '15% de descuento en el Cold Brew cítrico y el Frappé Nube todos los viernes del año, durante todo el día y en todos los canales de venta disponibles.',
    startsAt: null,
    endsAt: null,
    active: true,
    metadata: {
      days: ['FRIDAY'],
      discountPercentage: 15,
      productSlugs: ['cold-brew-citrico', 'frappe-nube'],
      stackable: false,
    },
  },
] as const;

export const cafeNubeFaqs = [
  {
    slug: 'horario-atencion',
    category: 'HOURS',
    question: '¿Cuál es el horario de atención?',
    answer:
      'Atendemos de lunes a viernes de 7:00 a. m. a 9:00 p. m., los sábados de 8:00 a. m. a 9:00 p. m. y los domingos y feriados de 8:00 a. m. a 8:00 p. m. La cocina cierra 30 minutos antes, pero seguimos preparando bebidas hasta el cierre.',
    active: true,
    metadata: {
      searchPhrases: [
        'a qué hora abren',
        'a qué hora cierran',
        'hasta qué hora atienden',
        'cuál es el horario del local',
        'atienden los domingos',
        'abren los feriados',
        'horario de atención de hoy',
        'a qué hora cierra la cocina',
      ],
    },
  },
  {
    slug: 'ubicacion',
    category: 'LOCATION',
    question: '¿Dónde están ubicados?',
    answer:
      'Estamos en Av. José Larco 880, Miraflores, Lima, cerca del cruce con Av. 28 de Julio. Puedes consultar la ubicación de referencia en Google Maps: https://www.google.com/maps/search/?api=1&query=Av.%20Jos%C3%A9%20Larco%20880%2C%20Miraflores%2C%20Lima. No contamos con estacionamiento propio.',
    active: true,
    metadata: {
      address: 'Av. José Larco 880',
      district: 'Miraflores',
      city: 'Lima',
      country: 'Perú',
      mapsUrl:
        'https://www.google.com/maps/search/?api=1&query=Av.%20Jos%C3%A9%20Larco%20880%2C%20Miraflores%2C%20Lima',
      searchPhrases: [
        'cómo llego al local',
        'cómo llegar a la cafetería',
        'dónde queda el local',
        'cuál es la dirección',
        'envíame la ubicación',
        'ubicación en Google Maps',
      ],
    },
  },
  {
    slug: 'sucursales',
    category: 'LOCATION',
    question: '¿Tienen otros locales o sucursales?',
    answer:
      'Actualmente contamos con un único local, ubicado en Miraflores, Lima. No tenemos sucursales en otros distritos ni ciudades.',
    active: true,
    metadata: {
      locationCount: 1,
      onlyLocationDistrict: 'Miraflores',
      otherBranches: false,
    },
  },
  {
    slug: 'metodos-pago',
    category: 'PAYMENTS',
    question: '¿Qué métodos de pago aceptan?',
    answer:
      'Aceptamos efectivo, tarjetas Visa, Mastercard y American Express, además de pagos con Yape y Plin.',
    active: true,
    metadata: {
      searchPhrases: [
        'cómo pago mi pedido',
        'con qué puedo pagar',
        'aceptan tarjeta',
        'aceptan Yape o Plin',
      ],
    },
  },
  {
    slug: 'delivery',
    category: 'DELIVERY',
    question: '¿Realizan delivery?',
    answer:
      'Sí. Realizamos delivery a todo Miraflores. Los pedidos se coordinan por WhatsApp. El costo depende de la dirección y el tiempo estimado es de 35 a 60 minutos. El servicio está sujeto a disponibilidad de repartidores y condiciones del tránsito.',
    active: true,
    metadata: {
      coverage: ['Miraflores'],
      estimatedMinutes: { min: 35, max: 60 },
      orderChannel: 'WHATSAPP',
      serviceSummary: 'delivery disponible en todo Miraflores',
    },
  },
  {
    slug: 'recojo-local',
    category: 'PICKUP',
    question: '¿Puedo pedir para recoger?',
    answer:
      'Sí. Puedes realizar un pedido por WhatsApp y recogerlo en el local. El tiempo habitual de preparación es de 15 a 25 minutos, pero puede aumentar en horas de mayor demanda.',
    active: true,
    metadata: {
      estimatedMinutes: { min: 15, max: 25 },
      orderChannel: 'WHATSAPP',
      serviceSummary: 'pedidos para recojo en el local',
    },
  },
  {
    slug: 'opciones-vegetarianas-leches-vegetales',
    category: 'DIETARY_OPTIONS',
    question: '¿Tienen opciones vegetarianas o leches vegetales?',
    answer:
      'Sí. La carta incluye opciones vegetarianas y veganas identificadas por producto. Entre las opciones veganas están el tostón palteado y la galleta vegana de avena y cacao. Las bebidas con leche pueden prepararse con leche de avena o almendras por S/ 3 adicionales, sujeto a disponibilidad.',
    active: true,
    metadata: {
      alternativeMilks: ['avena', 'almendras'],
      alternativeMilkPrice: '3.00',
    },
  },
  {
    slug: 'alergenos',
    category: 'ALLERGENS',
    question: '¿Cuál es su política sobre alérgenos y contaminación cruzada?',
    answer:
      'Los productos pueden contener o entrar en contacto con leche, gluten, huevo, frutos secos y sésamo. Se preparan en espacios compartidos, por lo que no podemos garantizar la ausencia total de trazas o contaminación cruzada. Si tienes una alergia, indícanos cuál antes de ordenar para revisar los ingredientes declarados de cada producto.',
    active: true,
    metadata: {
      allergens: ['leche', 'gluten', 'huevo', 'frutos secos', 'sésamo'],
      crossContaminationPossible: true,
      searchPhrases: [
        'política de alérgenos',
        'información sobre alergias',
        'qué productos no contienen gluten',
        'hay riesgo de contaminación cruzada',
      ],
    },
  },
  {
    slug: 'wifi',
    category: 'AMENITIES',
    question: '¿Tienen wifi?',
    answer:
      'Sí. Tenemos wifi gratuito para clientes durante su visita. Puedes solicitar la clave al personal.',
    active: true,
    metadata: {
      wifi: true,
      serviceSummary: 'wifi gratuito para clientes durante su visita',
    },
  },
  {
    slug: 'mascotas',
    category: 'AMENITIES',
    question: '¿Son pet friendly?',
    answer:
      'Sí, somos pet friendly. Los perros, gatos y otras mascotas son bienvenidos en la terraza y deben permanecer acompañados. El acceso al interior se reserva para animales de asistencia.',
    active: true,
    metadata: {
      petFriendlyArea: 'Terraza',
      indoorAccess: 'ASSISTANCE_ANIMALS_ONLY',
      serviceSummary: 'espacio pet friendly para mascotas en la terraza',
    },
  },
] as const;

export const obsoleteCafeNubeFaqSlugs = ['wifi-mascotas'] as const;
